TC Sprint-1
TonoyGT/JS-Winter-Cucumber-2023 pull request #3
Opened 2023-04-11 06:38 UTC by TonoyGT

2023-04-11 17:13 UTC, ahsansiddiki commented
For next PR put very high level description of the task on Description box above. Its professional.

2023-04-11 18:11 UTC, ahsansiddiki requested changes

2023-04-11 18:11 UTC, ahsansiddiki commented on Tests/Hotels/Homepage.feature
> +    Then I click on Travelers
Then => And
This is repeated Action step

2023-04-11 18:11 UTC, ahsansiddiki commented on Tests/Hotels/Homepage.feature
> +    Then I Select “Children” as 2
Then => And
This is repeated Action step

2023-04-11 18:11 UTC, ahsansiddiki commented on Tests/Hotels/Homepage.feature
> +    And I Verify Children-age dropdown are 2
And => Then
This is verification step.

2023-04-11 18:11 UTC, ahsansiddiki commented on Tests/Hotels/Homepage.feature
> +    Then I Verify Plus Button is enabled
Then => And

2023-04-11 18:11 UTC, ahsansiddiki commented on Tests/Hotels/Homepage.feature
> +    Then I Select “Children” as 6
Then => When
This is Action step

2023-04-11 18:11 UTC, ahsansiddiki commented on Tests/Hotels/Homepage.feature
> +    And I Verify Children-age dropdown are 6
And => Then

2023-04-11 18:11 UTC, ahsansiddiki commented on Tests/Hotels/Homepage.feature
> +    Then I Verify Plus Button is disabled
Then => And

2023-04-11 18:11 UTC, ahsansiddiki commented on Tests/Hotels/Homepage.feature
> +    Then I Select “Children” as 5
Then => When

2023-04-11 18:11 UTC, ahsansiddiki commented on Tests/Hotels/Homepage.feature
> +    And I Verify Children-age dropdown are 5
And => Then

2023-04-11 18:11 UTC, ahsansiddiki commented on Tests/Hotels/Homepage.feature
> +    Then I Verify Plus Button is enabled
Then => And
This is repeated verification step

2023-04-11 18:11 UTC, ahsansiddiki commented on Tests/Hotels/Homepage.feature
> +    Then I Select “Children” as 0
Then => When

2023-04-11 18:11 UTC, ahsansiddiki commented on Tests/Hotels/Homepage.feature
> +    And I Verify Children-age dropdown is NOT displayed
And => Then

2023-04-11 18:11 UTC, ahsansiddiki commented on Tests/Hotels/Homepage.feature
> +    Then I Verify Plus Button is enabled
Then => And

2023-04-11 18:11 UTC, ahsansiddiki commented on Tests/Hotels/Homepage.feature
> +    Then I Verify Plus Button is enabled
Follow the same style for all other scenarios

2023-04-11 18:11 UTC, ahsansiddiki commented on Tests/Hotels/Homepage.feature
> +  Scenario Outline: Verify user can update number of guests on Home page
This Scenario not Scenario Outline. Scenario Outline should have an Example data table.
Scenario Outline => Scenario

2023-04-11 18:11 UTC, ahsansiddiki commented on Tests/Hotels/Homepage.feature
> +  Scenario Outline: Verify error is displayed when user submits the empty feedback form
Scenario Outline => Scenario

2023-04-11 18:11 UTC, ahsansiddiki commented on Tests/Hotels/Homepage.feature
> +  Scenario Outline: Verify user can submit feedback after completing the feedback form
Scenario Outline => Scenario

2023-04-11 18:11 UTC, ahsansiddiki commented on StepDefinitions/Hotels/FeedbackPageSD.js
> +Then(/^I Click “Feedback”$/, async function () {
Then => When
All action should be labelled as When in SD files.

2023-04-11 18:11 UTC, ahsansiddiki commented on StepDefinitions/Hotels/FeedbackPageSD.js
> +    await browser.pause(5000);
Using hard coded wait period isn't professional. You can use another element to be displayed/enabled. Pls try to remove all pause() eventually.

2023-04-11 18:11 UTC, ahsansiddiki commented on StepDefinitions/Hotels/FeedbackPageSD.js
> +    }
No coding in SD files. Above code should go in a function in related pageObject files. Then call the function here. Also you can reuse that function in L54.

2023-04-11 18:11 UTC, ahsansiddiki commented on Pages/Hotels/FeedbackPage.js
> +async switchWindow() {
switchWindow name isn't appropriate bcz you're not switching here just getting window handles. So name could be something like getAllWindowHandles().
Or 
You can pass the expected url/partOfUrl in this function as parameter and run that loop inside this func to do actual switch.

2023-04-11 18:11 UTC, ahsansiddiki commented on Pages/Hotels/FeedbackPage.js
> + async didYouAnswer() {
didYouAnswer() => clickOnDidYouAnswer()
Make similar correction on function name where applicable. It look professional.

2023-04-11 18:11 UTC, ahsansiddiki commented on Pages/Hotels/SignupPage.js
> +    signinMenuLocator = '//div [@class="uitk-menu-container uitk-menu-open uitk-menu-pos-right uitk-menu-container-autoposition uitk-menu-container-has-intersection-root-el"]'
Instead of using all class values, you can use contains() and use 1 or 2 class value.

2023-04-11 18:11 UTC, ahsansiddiki commented on Pages/Hotels/SignupPage.js
> +    keepMeSigninCheckboxLocator = '//div[@class="uitk-layout-flex uitk-layout-flex-flex-wrap-nowrap uitk-switch uitk-checkbox"]';
Same as above.

2023-04-12 09:49 UTC, TonoyGT reviewed
I changed as you told please check

2023-04-12 19:48 UTC, ahsansiddiki approved these changes

2023-04-12 19:48 UTC, ahsansiddiki commented on Tests/Hotels/Homepage.feature
> +    Then I Verify total number of Travelers is sum of adults and children as same as selected on step #3 and #4
You forgot to update Gherkin labels for other scenarios. Pls follow the way we did for first scenario.

2023-04-12 19:48 UTC, merged